import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { Theme } from "./lib/enums";
import isValidTheme from "./lib/validateTheme";
import { UserProvider } from "./lib/hooks/useUser";
import RootLayoutHeader from "./components/Root Layout Header/Header";
import { Hanuman } from "next/font/google";
import { PostHogProvider } from "./postHogProvider";

const hanuman = Hanuman({ subsets: ["latin"] });

/** Fonts to be chosen Later  */

export const metadata: Metadata = {
	title: "LOKI",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`scroll-smooth min-w-dvw ${hanuman.className}`}
			data-scroll-behavior="smooth">
			<body
				className={`antialiased relative  flex flex-col min-h-screen transition-colors duration-300 bg-neutral-900 text-neutral-100`}>
				<PostHogProvider>
					<UserProvider>
						<RootLayoutHeader />
						<div className="">{children}</div>
						<footer>
							<div className="w-full h-20 bg-brand-900 dark:bg-brand-900 fixed bottom-0  flex items-center justify-center">
								<p className="text-neutral-300 ">
									© 2024 Loki App. All rights reserved.
								</p>
							</div>
						</footer>
					</UserProvider>
				</PostHogProvider>
			</body>
		</html>
	);
}
