import express from "express";
import { router as dashboardRouter } from "./dashboard/index";
import { router as loggingRouter } from "./logging/index";
import { router as starboardRouter } from "./starboard/index";
import { router as bansRouter } from "./bans/index";
import { router as kicksRouter } from "./kicks/index";
import { router as timeoutsRouter } from "./timeouts/index";
import { router as warnsRouter } from "./warns/index";
import { router as ticketsRouter } from "./tickets/index";
import { router as mutesRouter } from "./mutes/index";
import { router as throwRouter } from "./throw/index";
export const router = express.Router({ mergeParams: true });

router.use("/dashboard", dashboardRouter);
router.use("/logging", loggingRouter);
router.use("/starboard", starboardRouter);
router.use("/bans", bansRouter);
router.use("/kicks", kicksRouter);
router.use("/timeouts", timeoutsRouter);
router.use("/warns", warnsRouter);
router.use("/tickets", ticketsRouter);
router.use("/mutes", mutesRouter);
router.use("/throw", throwRouter);
